#!/bin/zsh

# XDG export XDG_DESKTOP_DIR="$HOME/"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# help zsh find configs
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# default apps
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"
export FILE="ranger"
export STATUSBAR="polybar"

# some of these are used in paths
source $ZDOTDIR/exports

# path
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH="$PATH:$CARGO_HOME"/bin
export PATH="$PATH:$GOPATH"/bin

# start X
# uncomment for sway
#if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
#  exec sway && $XDG_CONFIG_HOME/wayland/initrc
#fi

[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx "$XDG_CONFIG_HOME/X11/xinitrc"
