#!/usr/bin/zsh

$XDG_CONFIG_HOME/X11/xprofile

# gpg nonsense
/etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# until better times
#gpgconf --launch gpg-agent
#export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

ssh-agent i3
