#!/usr/bin/zsh

# polybar forgets fonts
fc-cache -f &

xwallpaper --zoom ~/.local/share/wallpapers/melody.png
xrdb ~/.config/X11/Xresources &
xcompmgr &                      # transparency
dunst &                         # notifications
flameshot &
