#!/usr/bin/zsh

export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl

export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

# polybar forgets fonts
fc-cache -f &

#xwallpaper --zoom ~/.local/share/wallpapers/venture2.png
#xrdb ~/.config/X11/Xresources &
#xcompmgr &                      # transparency
dunst &                          # notifications

ssh-agent sway
